name: tf
channels:
  - defaults
  - conda-forge
dependencies:
  - nomkl
  - affine
  - bzip2
  - click
  - coverage
  - cryptography
  - flake8
  - future
  - gdal=3.4.3
  - geopandas
  - jupyter
  - matplotlib
  - numpy
  - libiconv
  - pandas
  - geopandas>=0.10
  - pip
  - pygeos
  - fiona
  - scikit-image
  - scikit-learn
  - tensorboard
  - tqdm
  - rasterio=1.2.10
  - proj>=7
  - pyproj>=3
  - proj-data
  - pip:
    - opencv-python
    - geopy
    - ipdb
    - openpyxl
    - python-dateutil
