name: si
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - cudatoolkit=10.2
  - pytorch=1.12.1 
  - torchvision=0.13.1
  - gdal=3.4.3
  - jupyter
  - matplotlib
  - numpy
  - geopandas>=0.10
  - pip
  - fiona
  - scikit-image
  - scikit-learn
  - tensorboard
  - tqdm
  - rasterio=1.2.10
  - pip:
    - opencv-python
    - geopy
    - ipdb
    - openpyxl
    - python-dateutil
